language: android

android:
    components:
        - tools
        - build-tools-28.0.2
        - android-26
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

jdk:
    - oraclejdk8
script:
    - ./gradlew build
